//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace app_crm
{
    using System;
    using System.Collections.Generic;
    
    public partial class dd_empresa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dd_empresa()
        {
            this.dd_usuarios = new HashSet<dd_usuarios>();
        }
    
        public System.Guid empresaID { get; set; }
        public Nullable<int> estatusID { get; set; }
        public string nombre { get; set; }
        public string telefono { get; set; }
        public string email { get; set; }
        public string callenum { get; set; }
        public Nullable<int> id_codigo { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
    
        public virtual fact_estatus fact_estatus { get; set; }
        public virtual dd_sepomex dd_sepomex { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dd_usuarios> dd_usuarios { get; set; }
    }
}
