//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace app_crm
{
    using System;
    using System.Collections.Generic;
    
    public partial class dd_usuarios
    {
        public System.Guid usuarioID { get; set; }
        public Nullable<int> estatusID { get; set; }
        public Nullable<int> generoID { get; set; }
        public Nullable<int> tipo_usuarioID { get; set; }
        public string nombres { get; set; }
        public string a_paterno { get; set; }
        public string a_materno { get; set; }
        public string codigo_usuarios { get; set; }
        public string clave { get; set; }
        public Nullable<System.DateTime> fecha_nacimiento { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
        public System.Guid empresaID { get; set; }
    
        public virtual dd_empresa dd_empresa { get; set; }
        public virtual fact_estatus fact_estatus { get; set; }
        public virtual fact_genero fact_genero { get; set; }
        public virtual fact_tipo_usuario fact_tipo_usuario { get; set; }
    }
}
