//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace app_crm
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db_crmEntities : DbContext
    {
        public db_crmEntities()
            : base("name=db_crmEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<dd_empresa> dd_empresa { get; set; }
        public virtual DbSet<dd_sepomex> dd_sepomex { get; set; }
        public virtual DbSet<dd_usuarios> dd_usuarios { get; set; }
        public virtual DbSet<fact_estatus> fact_estatus { get; set; }
        public virtual DbSet<fact_genero> fact_genero { get; set; }
        public virtual DbSet<fact_mensajes> fact_mensajes { get; set; }
        public virtual DbSet<fact_tipo_usuario> fact_tipo_usuario { get; set; }
    }
}
